---

- name: install specific Fail2Ban version for Debian
  apt:
    pkg: 'fail2ban={{ fail2ban_pkg_version }}'
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian' and fail2ban_pkg_version is defined and fail2ban_pkg_version

- name: install current/latest Fail2Ban version for Debian
  apt:
    pkg: fail2ban
    state: '{{ fail2ban_pkg_state }}'
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian' and (fail2ban_pkg_version is not defined or fail2ban_pkg_version == '')

- name: install specific Fail2Ban version for RedHat
  yum:
    name: 'fail2ban={{ fail2ban_pkg_version }}'
    state: installed
  when: ansible_os_family == 'RedHat' and fail2ban_pkg_version is defined and fail2ban_pkg_version

- name: install current/latest Fail2Ban package for RedHat
  yum:
    name: fail2ban
    state: '{{ fail2ban_pkg_state }}'
  when: ansible_os_family == 'RedHat' and (fail2ban_pkg_version is not defined or fail2ban_pkg_version == '')
